language: python
python: '2.7'
sudo: required
addons:
  apt:
    packages:
    - python-pip
install:
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- ansible-playbook tests/test.yml -i tests/inventory --syntax-check
- ansible-playbook tests/test.yml -i tests/inventory --connection=local
- |
  ansible-playbook tests/test.yml -i tests/inventory --connection=local | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: fg8z8fuYOwHH5iaPSWOyx+UdaB2FnmVhUDw8WsRXsBMo6+GG82NmvLpgk0bmWogZe1Mk8gPE9GNKvJwuoOpaSo3T1Vz1Be+oPxZSvvrbMgQoJt/S3xwIt9tGHHVhuJ74iwaUvd07a9DH33L8LEkLrHQlmb3MkdV4K6uBTm+b/p9W1tPREN6S02AIJhudPpe9Kq2ggSl7UqNKRqvpP5oYjlCjY7OM4HNyAyM+tzJ/qXdG3Gjbrj51pefAuT4wsRy4obdLzk2CrEb1Ao1LDzBTOswQhMeU/Q6SHelzsv+768gg3QvsG0PvEMc+/wxSvC/aYhwVjjbfKGSgcZx0twB+ilVqXEaTHZor6d6JluWJ+6XED+mNN03zyQB3bU/5rhaX9QE6KBgQbQlIlGmgoH4r4YENj4p8B/5pV5OMs0QGkpVJk3xlK2svEfGM1TYUsOQCb84v70u3z6Qix2n733s1vG4a9cFqm3Ot/BH/kmsHzVqJILQfbXh/somOoonnOontvZWuJ6v/Qn7ELiTZ/gBJ53Jvb40b2uCFSuWExpQYvEwWBcAR1lnmtejCwdGP854eVKteWGrQr/fsPv1nQqPDOFNxc/MqF29CNJg+GY6eiJ+VAKfyvr2R641iTMR0dKEmRGf99kdIxr+wqSLnV4FdNhK/CG4IGpJJwYGXtD0ybGA=
