---
- name: update apt-get
  apt: update_cache=yes

- name: Install software-properties-common
  apt: name=software-properties-common

- name: update repository
  apt_repository: repo='ppa:brightbox/ruby-ng' state=present

- name: update apt-get
  apt: update_cache=yes

- name: Install rubies
  apt: name={{ item }}
  with_items: "{{ ruby.versions }}"

- name: Install ruby-switch
  apt: name=ruby-switch state=present

- name: check default ruby version
  shell: ruby -v
  register: current_ruby_version
  changed_when: False
  always_run: yes

- name: Set default ruby
  become: yes
  shell: ruby-switch --set "ruby{{ ruby.default }}"
  when: ruby.default not in current_ruby_version.stdout
