---
- name: update apt-get
  apt: update_cache=yes

- name: Install software-properties-common
  apt: name=software-properties-common

- name: update repository
  apt_repository: repo='ppa:brightbox/ruby-ng' state=present

- name: update apt-get
  apt: update_cache=yes

- name: Install rubies
  apt: name={{ item }}
  with_items: "{{ ruby.versions }}"

- name: Install ruby-switch
  apt: name=ruby-switch state=present

- name: Set default ruby
  sudo: true
  shell: ruby-switch --set "{{ ruby.default }}"
